name: Deploy via FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          # ftp server
          server: ${{ secrets.FTP_SERVER }}
          # ftp username
          username: ${{ secrets.FTP_USERNAME }}
          # ftp password
          password: ${{ secrets.FTP_PASSWORD }}
          # Server port to connect to
          port: 31000 # optional
          # protocol to deploy with - ftp, ftps, or ftps-legacy
          protocol: # optional
          # Folder to upload from, must end with trailing slash /
          local-dir: # optional
          # Path to upload to on the server. Must end with trailing slash /
          server-dir: # optional
          # Path and name of the state file
          state-name: # optional
          # Prints modifications without making changes
          dry-run: # optional
          # Deletes ALL contents of server-dir
          dangerous-clean-slate: # optional
          # Glob patterns to exclude from publish/delete
          exclude: # optional
          # minimal, standard, or verbose
          log-level: # optional
          # strict or loose
          security: # optional
          # Timeout in milliseconds
          timeout: # optional
